paths = ['#src']
flags = ['-Werror', '-g']
libs = ['opencv_core', 'opencv_highgui', 'opencv_imgproc', 'opencv_nonfree', 'opencv_features2d', 'opencv_ml']
libpaths = []

#Source files
clustering_sources = Split('''
clustering.cc
''')

#Source files
bow_sources = Split('''
bow.cc
''')

#Source files
classify_sources = Split('''
classify.cc
''')

#Source files
test_sources = Split('''
testing.cc
''')

Program('../bin/make_vocabulary', clustering_sources, CPPPATH=paths, CPPFLAGS=flags, LIBPATH=libpaths, LIBS=libs)
Program('../bin/bow', bow_sources, CPPPATH=paths, CPPFLAGS=flags, LIBPATH=libpaths, LIBS=libs)
Program('../bin/classify', classify_sources, CPPPATH=paths, CPPFLAGS=flags, LIBPATH=libpaths, LIBS=libs)
Program('../bin/test', test_sources, CPPPATH=paths, CPPFLAGS=flags, LIBPATH=libpaths, LIBS=libs)
